R/auto.R
As discussed in #36 
fixes #37
=> pre_release(): mention to clean up NEWS.md from dev entries

R/auto.R, R/bump-version.R, R/finalize-version.R, R/update-news.R, R/update-version.R
I used h1 to add some context of the intermediate steps within `pre_release()`.
Also I turned of the chatty usethis path printout.
#38
=> {cli}ify `pre_release()`

R/auto.R
=> Push release version to main branch before bumping to dev again

vignettes/demo.Rmd
Otherwise R CMD Check errors locally for me.
=> demo.Rmd: master -> main

R/api-update-news.R, R/commit-version.R, R/commits.R, R/finalize-version.R
=> Merge back PR target branch

README.Rmd
=> Add .Rprofile mention

README.Rmd, README.md
It should look better once knit. :grin:
=> Fix code coverage badge

DESCRIPTION, R/api-update-news.R, R/bump-version.R, R/commit-version.R, R/tag-version.R, R/update-news.R, R/update-version.R, man/update_news.Rd, tests/testthat/_snaps/update-news/NEWS-empty.md, tests/testthat/_snaps/update-news/NEWS-new.md, tests/testthat/test-update-news.R
Fix #150
Fix #151 (for mocking!)
=> support empty/absent news file

DESCRIPTION, README.Rmd, README.md
should the CRAN badge be removed as it's a 404 for now?
=> URL checks

R/api-bump-version.R, R/api-finalize-version.R, R/api-tag-version.R, R/api-unbump-version.R, R/api-update-news.R, R/api-update-version.R, R/repo-helper.R, man/bump_version.Rd, man/finalize_version.Rd, man/tag_version.Rd, man/unbump_version.Rd, man/update_news.Rd, man/update_version.Rd, man/with_demo_project.Rd
Also h/t https://github.com/DavisVaughan/extrachecks
=> add return value

.Rbuildignore, README.Rmd, README.md, cran-comments.md
=> CRAN preparedness

R/tag-version.R, tests/testthat/_snaps/demo/demo.md
Fix  #176
Sorry, my refactoring had created this error!
=> fix for vignette

README.Rmd, README.md, man/rmd-fragments/setup.Rmd
Note I haven't knit the README.
These are the last remaining items in  #109
=> CRAN installation

R/auto.R, R/bump-version.R, R/gh-helpers.R, R/submit.R, R/tag-version.R
for replacing `usethis::use_github_release()`.
=> Extract functions

DESCRIPTION
=> Parallel tests

DESCRIPTION
@maelle: this may lead to conflicts all over the place, let's apply when you have no more open PRs.
=> Parallel tests and automatic styling

.github/workflows/style/action.yml, DESCRIPTION, R/bg.R
=> chore: Enable auto-style on GitHub Actions

.github/workflows/netlify.yaml
=> chore: Turn Netlify builds off for now

R/update-news.R, tests/testthat/_snaps/update-news.md
=> FIX: Add PR number to CC messages

R/update-news.R, tests/testthat/_snaps/update-news/NEWS.md
=> fix: Adjust empty lines and space in update_news()

R/update-news.R, R/utils.R, tests/testthat/_snaps/demo/demo.md, tests/testthat/_snaps/update-news.md, tests/testthat/_snaps/update-news/NEWS.md, tests/testthat/test-update-news.R
=> feat: capitalize first letter of each bullet

README.md, man/rmd-fragments/summary.Rmd
=> docs: fix typo in README

README.md, man/rmd-fragments/summary.Rmd
=> docs: update summary of how fledge uses commit messages

.github/workflows/fledge.yaml
@krlmlr btw fledge is super behind on version bumping :sweat_smile: (which is actually very handy for interactive testing but not the best example :sweat_smile: )
=> ci: create fledge.yaml

README.Rmd, README.md, man/rmd-fragments/related-tools.Rmd
Related to https://github.com/kapsner/autonewsmd/issues/3
=> docs: add README section on related tools

R/update-news.R, R/utils-gh-pat.R, tests/testthat/_snaps/bump_version.md, tests/testthat/_snaps/demo/demo.md, tests/testthat/_snaps/unbump_version.md, tests/testthat/_snaps/update-news.md, tests/testthat/test-update-news.R
=> fix: Relax requirement for GitHub PAT scope

DESCRIPTION
=> chore: store downlit info

R/update-news.R, tests/testthat/_snaps/update-news.md, tests/testthat/_snaps/update-news/NEWS-merge.md, tests/testthat/_snaps/update-news/NEWS.md, tests/testthat/test-update-news.R
=> feat: Add full stop to messages

R/unbump-version.R, R/update-news.R
=> fix: Remove partial matching warning

NEWS.md
Where is the styling bot name defined?
=> Remove false Markdown link?

DESCRIPTION, R/auto.R
=> chore: Move foghorn and rversions to Suggests

R/auto.R, R/bump-version.R, R/commit-version.R, R/commits.R, R/fledgling.R, R/gh-helpers.R, R/pandoc.R, R/parse-news-items.R, R/repo-helper.R, R/submit.R, R/tag-version.R, R/update-news.R, R/utils-gh-pat.R, tests/testthat/_snaps/bump_version.md, tests/testthat/_snaps/parse-news-items.md, tests/testthat/_snaps/tag_version.md, tests/testthat/_snaps/with_demo_project.md, tests/testthat/helper-snapshot.R
=> refactor: use the full power of {cli}

R/fledgling.R, tests/testthat/_snaps/fledgling.md, tests/testthat/test-fledgling.R
=> feat: add ability to parse two-line headers

DESCRIPTION, R/auto.R, R/utils.R
Fix #648 
Is this where this code should live?
=> feat: New internal `release_after_cran_built_binaries()` to support automated CRAN release from GHA

R/parse-news-items.R, R/repo-helper.R, R/update-news.R, tests/testthat/_snaps/update-news.md, tests/testthat/_snaps/update-news/newchangelog.md, tests/testthat/test-update-news.R
=> feat: do not write "Same as previous version" as first thing in a brand-new changelog

R/auto.R
=> refactor: slightly simplify pre_release()

R/fledgling.R, R/repo-helper.R, R/update-news.R, man/create_demo_project.Rd, tests/testthat/_snaps/demo/demo.md, tests/testthat/test-bump_version.R, tests/testthat/test-finalize-version.R, tests/testthat/test-parse-news-items.R, tests/testthat/test-tag_version.R, tests/testthat/test-unbump_version.R, tests/testthat/test-update-news.R
=> fix: adapt to new behavior of usethis::use_news_md()

R/auto.R, tests/testthat/test-auto.R
Via https://github.com/igraph/rigraph/pull/803#issuecomment-1567891022
=> feat: more flexible version extraction from release PR title

tests/testthat/helper-conventional-commits.R
=> test: add a test for upper case conventional commit type

DESCRIPTION, R/auto.R, R/parse-news-items.R, R/submit.R
=> refactor: replace httr with httr2

R/update-news.R
@maelle: Is this code path tested?
=> chore: More efficient data frame access

R/auto.R
=> fix: Check if release exists before creating

R/api-bump-version.R, R/api-update-news.R, R/auto.R, R/bump-version.R, R/finalize-version.R, R/parse-news-items.R, R/update-news.R, R/utils-git.R, tests/testthat/_snaps/bump_version.md, tests/testthat/_snaps/demo/demo.md, tests/testthat/_snaps/unbump_version.md, tests/testthat/_snaps/utils-git.md, tests/testthat/test-utils-git.R
=> chore: Refactorings for #686

R/commit-version.R, tests/testthat/_snaps/commit-version.md, tests/testthat/test-commit-version.R
@maelle: Can you please add tests if needed?
=> chore: Pretty `check_only_modified()`

R/api-update-news.R, R/bump-version.R, R/commits.R
=> chore: `no_change()` and other functions gain ref argument

R/auto.R, R/submit.R
=> fix: Extract error from first submission step, fix CRAN submission

R/auto.R, R/utils-gh-pat.R, inst/marshmallow-2.R, inst/marshmallow.R
=> test: Basic testing scripts

R/auto.R, R/bump-version.R, inst/marshmallow-along.R
All related to chattiness somehow.
=> feat: More extensive preflight checks in `post_release()`, reduce output in quiet mode

R/auto.R, R/fledgling.R, tests/testthat/_snaps/auto/NEWS.md, tests/testthat/test-auto.R
=> feat: Automatically merge news from dev versions before release

R/auto.R, tests/testthat/_snaps/auto.md
=> feat: `post_release()` is independent from release branch

R/utils-parse-version.R, tests/testthat/_snaps/utils-parse-version.md, tests/testthat/test-utils-parse-version.R
=> feat: Allow bumping straight from released version

DESCRIPTION, R/api-update-news.R, R/bump-version.R, R/update-news.R, R/zzz.R, tests/testthat/_snaps/auto.md
=> chore: Move responsibility for writing fledgeling, memoise, add `repo` argument

.github/workflows/install/action.yml, R/repo-helper.R, R/utils-git.R, tests/testthat/_snaps/unbump_version.md, tests/testthat/helper-commits.R, tests/testthat/helper-conventional-commits.R, tests/testthat/test-auto-full-cycle-pre.R, tests/testthat/test-auto-full-cycle.R, tests/testthat/test-auto-pre.R, tests/testthat/test-auto-release-abandon.R, tests/testthat/test-auto.R, tests/testthat/test-bump_version.R, tests/testthat/test-finalize-version.R, tests/testthat/test-full-cycle-main-nopush.R, tests/testthat/test-full-cycle-main.R, tests/testthat/test-parse-news-items.R, tests/testthat/test-tag_version.R, tests/testthat/test-unbump_version.R, tests/testthat/test-update-news.R
https://github.com/r-lib/gert/issues/242
=> test: Speed up tests by replacing `gert::git_add()` with a system call

R/auto.R, R/fledgling.R, R/update-news.R
We can do most (everything?) through that column, moving forward.
=> chore: Keep `raw` component up to date, use it for assembling the NEWS
